### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by DavePearce** [Whiley/Whiley2Boogie#145]
Verifying Minesweeper is currently giving this error:

```
[INFO] Java output "Exception in thread "main" java.lang.IllegalArgumentException: unrecognised error: '/tmp/main14355793700442895970.bpl(653,202): Error: invalid type for argument 2 in call to m_apply$m2Q6stringQ13EventListenerV: Lambda (expected: w3c$dom$EventListener$u3mQ5EventVmQ10MouseEventVmQ13KeyboardEventV)'
	at wyboogie.util.Boogie.parseErrors(Boogie.java:354)
	at wyboogie.util.Boogie.check(Boogie.java:205)
	at wyboogie.tasks.BoogieBuildTask.verify(BoogieBuildTask.java:141)
	at wyboogie.tasks.BoogieBuildTask.run(BoogieBuildTask.java:134)
	at wyboogie.Main.run(Main.java:139)
	at wyboogie.Main.main(Main.java:200)
"
wyboogie: Exception in thread "main" java.lang.IllegalArgumentException: unrecognised error: '/tmp/main14355793700442895970.bpl(653,202): Error: invalid type for argument 2 in call to m_apply$m2Q6stringQ13EventListenerV: Lambda (expected: w3c$dom$EventListener$u3mQ5EventVmQ10MouseEventVmQ13KeyboardEventV)'
	at wyboogie.util.Boogie.parseErrors(Boogie.java:354)
	at wyboogie.util.Boogie.check(Boogie.java:205)
	at wyboogie.tasks.BoogieBuildTask.verify(BoogieBuildTask.java:141)
	at wyboogie.tasks.BoogieBuildTask.run(BoogieBuildTask.java:134)
	at wyboogie.Main.run(Main.java:139)
	at wyboogie.Main.main(Main.java:200)

```

**Comment by DavePearce** [comment]
Caused by this line in `main.whiley`:

```Whiley
    c->addEventListener("click",&(MouseEvent e -> onclick_handler(e,state,window)))
```

**Comment by DavePearce** [comment]
**Question**:  Is this just a duplicate of #59?

**Comment by DavePearce** [comment]
The problem seems to be with the type given for a lambda, like this:

```
const unique lambda#255 : Lambda;
```

The corresponding application, however, is typed like this:

```
procedure m_apply$m2aIQ7handlerV(l : Lambda, p#0 : [int]Any, p#1 : main$handler$u2mQ5StateVmIV);
```

I think we need some kind of boxing going on here?

**Comment by DavePearce** [comment]
**UPDATE:** for the example in #59 introducing a `Lambda#box()` does indeed solve the problem.

**Comment by DavePearce** [comment]
Furthermore, the problem seems to be more specific to boxing parameters for lambdas ?

**Comment by DavePearce** [comment]
This is the minimal example:

```Whiley
type State is {int x}
type handler is method(State)|method(int)
type fn is function(handler)->(int)

method register(fn f):
    f(&(State s -> empty()))

method empty():
    skip
```

Note that it _requires_ a lambda application as a statement.  It won't fail if we have e.g. `int x = f(..)`

**Comment by DavePearce** [comment]
This isn't actually fixed yet though.
